# Generated by Django 5.0.2 on 2025-06-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_franchise_alter_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$3WBOGUTT8YD07jPBckxONm$nKsx98/sNCH78QvqRQVwVa0nUaC1a7g+yOuBpk2G92w=', max_length=128),
        ),
    ]
